config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  resources :requests
  resources :events
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  before_action :set_quarter, only: [:show, :edit, :update, :destroy]

  # GET /quarters
  # GET /quarters.json
  def index
    @quarters = Quarter.all
  end

  # GET /quarters/1
  # GET /quarters/1.json
  def show
  end

  # GET /quarters/new
  def new
    @quarter = Quarter.new
  end

  # GET /quarters/1/edit
  def edit
  end

  # POST /quarters
  # POST /quarters.json
  def create
    @quarter = Quarter.new(quarter_params)

    respond_to do |format|
      if @quarter.save
        format.html { redirect_to @quarter, notice: 'Quarter was successfully created.' }
        format.json { render :show, status: :created, location: @quarter }
      else
        format.html { render :new }
        format.json { render json: @quarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quarters/1
  # PATCH/PUT /quarters/1.json
  def update
    respond_to do |format|
      if @quarter.update(quarter_params)
        format.html { redirect_to @quarter, notice: 'Quarter was successfully updated.' }
        format.json { render :show, status: :ok, location: @quarter }
      else
        format.html { render :edit }
        format.json { render json: @quarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quarters/1
  # DELETE /quarters/1.json
  def destroy
    @quarter.destroy
    respond_to do |format|
      format.html { redirect_to quarters_url, notice: 'Quarter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quarter
      @quarter = Quarter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quarter_params
      params.require(:quarter).permit(:zip_code, :name)
    end
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/views/quarters/_form.html.erb
<%= form_with(model: quarter, local: true) do |form| %>
  <% if quarter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quarter.errors.count, "error") %> prohibited this quarter from being saved:</h2>

      <ul>
        <% quarter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quarters/edit.html.erb
<h1>Editing Quarter</h1>

<%= render 'form', quarter: @quarter %>

<%= link_to 'Show', @quarter %> |
<%= link_to 'Back', quarters_path %>

app/views/quarters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quarters</h1>

<table>
  <thead>
    <tr>
      <th>Zip code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quarters.each do |quarter| %>
      <tr>
        <td><%= quarter.zip_code %></td>
        <td><%= quarter.name %></td>
        <td><%= link_to 'Show', quarter %></td>
        <td><%= link_to 'Edit', edit_quarter_path(quarter) %></td>
        <td><%= link_to 'Destroy', quarter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quarter', new_quarter_path %>

app/views/quarters/new.html.erb
<h1>New Quarter</h1>

<%= render 'form', quarter: @quarter %>

<%= link_to 'Back', quarters_path %>

app/views/quarters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zip code:</strong>
  <%= @quarter.zip_code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @quarter.name %>
</p>

<%= link_to 'Edit', edit_quarter_path(@quarter) %> |
<%= link_to 'Back', quarters_path %>