config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  resources :requests
  resources :events
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User'
	belongs_to :quarter
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :club
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :recrutement
	belongs_to :user
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         belongs_to :quarter, optional: true
         belongs_to :club, optional: true
         has_many :requests
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@quarters = Quarter.all
  	@clubs = Club.all
  	@events = Event.all
  	@recrutements = Recrutement.all
  	@requests = Request.all
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
        @club = Club.find(params[:id])
  end

  # GET /clubs/new
  def new 
    @user = current_user
        @quarters = Quarter.all
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
      @my_user = current_user.id
    @club = Club.create('name' => params[:name], 'category' => params[:category], quarter_id: params[:quarter_id])

  @club.admin_id =  @my_user

    respond_to do |format|
      if @club.save
        format.html { redirect_to new_club_picture_path(@club.id), notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@quarters = Quarter.all
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/recrutements_helper.rb
module RecrutementsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/_club.html.erb
 <% a = 0 %>
<% @clubs.each do |club| %>

  <% if club.admin.id == current_user.id %>
  <h1><%= link_to 'Mon club', club_path(club.id) %></h1>
    
  <% else %>
    <% a+= 1%>
  <% end %>
<% end %>
<%if a == @clubs.count %>
  <h1><%= link_to 'Créer un club', new_club_path %></h1>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scaff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <% if user_signed_in? && current_user.role === 'admin' %>
    <ul>
      <li><a href="/admin"> Espace Admin </a></li>
    </ul>

    <% end %>

    <ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      <%= link_to "Profil", user_path(current_user.id) %>
    </li>


    <li>
      


       <% a = 0 %>
<% Club.all.each do |club| %>

  <% if club.admin.id == current_user.id %>
  <a><%= link_to 'Mon club', club_path(club.id) %></a>
    
  <% else %>
    <% a+= 1%>
  <% end %>
<% end %>
<%if a == Club.all.count %>
  <a><%= link_to 'Créer un club', new_club_path %></a>
  
<% end %>




    </li>


    <li>
      <%= link_to "Liste des clubs", clubs_path %>
    </li>

  <li>
<%= link_to "Liste des recrutements", recrutements_path %>

 </li>
  <% else %>
    <li>    
      <%= link_to "Se connecter", new_user_session_path %>
    </li>

    <li>
      <%= link_to "S'inscrire", new_user_registration_path %>
    </li>


  <% end %>
</ul>
    <%= yield %>
 <h1>======================================================================================</h1>
  </body>
</html>